variant = "loose"

[[issues]]
file = "src/NavigationContainer.php"
code = "cyclomatic-complexity"
message = "Class has high complexity."
count = 1

[[issues]]
file = "src/NavigationContainer.php"
code = "kan-defect"
message = "Class has a high kan defect score."
count = 1

[[issues]]
file = "src/NavigationContainer.php"
code = "too-many-methods"
message = "Class has too many methods."
count = 1
